version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: postgres:17
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: